version: '3.7'

services:
  dm_db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  dm_web:
    build: .
    command: python /usr/src/dm_drf/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/dm_drf
    ports:
      - 8000:8000
    depends_on:
      - dm_db

volumes:
  postgres_data:
